version: '2'

services:
  website:
    build: .
    volumes:
      - .:/jebri-website
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
      - cable
    links:
      - postgres
      - redis
      - cable
    env_file:
      - 'config/production.env'

  postgres:
    image: postgres:9.5.4
    ports:
      - "5432:5432"
    env_file:
      - 'config/production.env'
    volumes:
      - postgres:/var/lib/postgresql/data

  cable:
    depends_on:
      - redis
    build: .
    command: puma -p 28080 cable/config.ru
    ports:
      - '28080:28080'
    volumes:
      - .:/petri-website
      - postgres:/var/lib/postgresql/data

    env_file:
      - 'config/production.env'

  redis:
    image: 'redis:3.2.3-alpine'
    command: echo never > /sys/kernel/mm/transparent_hugepage/enabled && redis-server --appendonly yes
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/var/lib/redis

volumes:
  redis-data:
    driver: local
  postgres:
    driver: local
  website:
      driver: local
